# Generated by Django 2.2.4 on 2019-08-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsApp', '0003_review_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='account',
            field=models.CharField(help_text='Введите ссылку на аккаунт блогера', max_length=200, null=True),
        ),
    ]
