# Generated by Django 2.2.4 on 2019-08-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsApp', '0004_auto_20190815_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='session_key',
        ),
        migrations.AlterField(
            model_name='review',
            name='blogger',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ReviewsApp.Person'),
        ),
        migrations.DeleteModel(
            name='Blogger',
        ),
    ]
