# Generated by Django 2.2.4 on 2019-08-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsApp', '0005_auto_20190815_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='ReviewsApp.Person'),
        ),
        migrations.AlterField(
            model_name='review',
            name='blogger',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogger', to='ReviewsApp.Person'),
        ),
    ]
